### ISSUE TITLE
works only for hyperplanes...

### ISSUE THREAD

**Issue by dimpase** [rschrecker/AffineGeometryDesign#1]
Your code only works for the design of hyperplanes; that is, e.g. `AffineGeometryDesign(3, 1, GF(2))`
will not return the right thing. In general, you always should remove a hyperplane from the respective projective geometry design, but a hyperplane need not be a block of the latter, as it can be a union of these.

**Comment by rschrecker** [comment]
sorry, sorted now

**Comment by dimpase** [comment]
did you test that change you made? it doesn't work for me.

**Comment by rschrecker** [comment]
It appears I was testing the original function instead of the one I wrote :,(
It seems to be working now though
